name: cross_local_storage
version: 3.0.0
homepage: https://github.com/marchdev-tk/cross_local_storage
description: SharedPreferences wrapper for both Mobile (Android/iOS), Web and Desktop (Windows, macOS, Linux). Also provides JSON file storage.

environment:
  sdk: '>=3.0.0 <5.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
